#entradas
nm_1=float(input("insertar nota primera tarea de matematicas: "))
nm_2=float(input("insertar nota segunda tarea de matematicas: "))
nm_3=float(input("insetar nota tercera tarea de matematicas: "))
nm_parcial=float(input("insertar nota del examen de matemáticas: "))
nf_1=float(input("insertar nota primera tarea de física: "))
nf_2=float(input("insertar nota segunda tarea de física: "))
nf_parcial=float(input("insertar nota del parcial de física: "))
nq_1=float(input("insertar nota primera tarea de quimica: "))
nq_2=float(input("insertar nota segunda tarea de quimica: "))
nq_3=float(input("insertar nota tercera tarea de quimica: "))
nq_parcial=float(input("insetar nota del parcial de quimica: "))
#caja negra 
nm_final=(((nm_1+nm_2+nm_3)/3)*0.10)+(nm_parcial*0.90)
nf_final=(((nf_1+nf_2)/2)*0.20)+(nf_parcial*0.80)
nq_final=(((nq_1+nq_2+nq_3)/3)*0.15)+(nq_parcial*0.85)
promedio=((nm_final+nf_final+nq_final)/3)
#salida
print(f"la nota final de matemáticas es: {nm_final} , la nota final de física es: {nf_final} y la nota final de quimica es: {nq_final}")
print("el promedio de las 3 materias es:"+str(promedio))